# Generated by Django 5.0.6 on 2024-05-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_alter_product_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(),
        ),
    ]
