# Generated by Django 5.0.6 on 2024-06-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='is_managed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
