# Generated by Django 5.0.6 on 2024-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_address_contactform_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
