# Generated by Django 5.0.6 on 2024-06-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_order_total_amount_alter_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='user',
        ),
    ]
