# Generated by Django 5.0.6 on 2024-06-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_customer_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='customer',
        ),
    ]
