# Generated by Django 5.0.6 on 2024-06-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_user_review_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='user',
        ),
    ]
